server:
  port: 7090
  servlet:
    context-path: /
spring:
  application:
    name: server
  cloud:
    consul:
      host: localhost
      port: 8500 
          
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
     application: ${spring.application.name} 
 